# SPDX-FileCopyrightText: 2026 AprilNEA LLC
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Commercial

[package]
name = "migration"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only OR LicenseRef-Commercial"
authors = ["AprilNEA <dev@aprilnea.me>"]

[features]
default = []
sqlx-postgres = ["sea-orm-migration/sqlx-postgres"]

[dependencies]
async-trait = "0.1"
sea-orm-migration = { version = "1.1", features = ["runtime-tokio-rustls"] }
